### ISSUE TITLE
Title is no longer reactive after 3.1.1

### ISSUE THREAD

**Issue by WarningImHack3r** [oekazuma/svelte-meta-tags#1010]
**Describe the bug**

After upgrading to 3.1.1 (#977), the `<title>` tag is no longer reactive if set from a reactive Svelte value

**Reproduction**
Provide a reproduction URL or steps to reproduce. If a report is vague and no reproduction is provided within a reasonable time-frame, the issue will be closed.

1. Create `let title = "myTitle"`
2. Use `<MetaTags {title} />`
3. Reactively change its value by binding it to some button or something
4. Notice the title doesn't update from a reactive update

(You can easily reproduce it by visiting https://svelte-changelog.vercel.app and switching the Svelte/SvelteKit/Other tab, if you downgrade your dependency locally the title changes on tab switch)

**Additional context**

**Comment by oekazuma** [comment]
I don't know if this is a Svelte bug or a spec, but it seems that if you enclose variables in `{#if}` within `<svelte:head>`, reactivity is lost.
As a tentative measure, I will try to solve this problem by enclosing variables with `{#key}`.
Svelte5 seems to have resolved this issue, so it will be resolved in the future.

**Comment by WarningImHack3r** [comment]
Thanks for your help and your reactivity!

**Comment by oekazuma** [comment]
A corrected version has been released!

https://github.com/oekazuma/svelte-meta-tags/releases/tag/svelte-meta-tags%403.1.2

**Comment by WarningImHack3r** [comment]
Thank you!! Keep up the good work :)
