### ISSUE TITLE
v4

### ISSUE THREAD

**Issue by oekazuma** [oekazuma/svelte-meta-tags#1015]
Below is a summary of what we need to do in v4.
If you have any requests you would like to see added to v4, please let me know.

- [x] #1197
  - Supports Svelte 5! With this change, we will no longer support Svelte 3 and Svelte 4.

- [x] #1119
  - Provide deep-merge functionality for objects, currently used independently by each user, within the package. 
  - The use of the deepMerge function provided by this library is not required, so you can continue to use whatever you like.
  
- [x] [add Twitter properties and rename `twitter.handle` to `twitter.creator`](https://github.com/oekazuma/svelte-meta-tags/pull/1200)
  - Add the rest of the twitter properties. Also rename `twitter.handle` to `twitter.creator` to match the actual interface. 

## Migration Guide

`twitter.handle` has been renamed `twitter.creator.`
This change aligns with the actual property name.

v3.x
```svelte
<MetaTags
  twitter={{
    handle: '@handle',
    site: '@site',
    cardType: 'summary_large_image',
    title: 'Twitter',
    description: 'Twitter',
    image: 'https://www.example.ie/twitter-image.jpg',
    imageAlt: 'Twitter image alt'
  }}
/>
```

v4
```svelte
<MetaTags
  twitter={{
    creator: '@handle',
    site: '@site',
    cardType: 'summary_large_image',
    title: 'Twitter',
    description: 'Twitter',
    image: 'https://www.example.ie/twitter-image.jpg',
    imageAlt: 'Twitter image alt'
  }}
/>
```

Add `deepMerge`, a function that deeply merges the enumerable properties of two or more objects.

The use of the deepMerge function provided by this library is not required, so you can continue to use whatever you like.

v3.x

`+layout.svelte`
```svelte
<script>
  import { MetaTags } from 'svelte-meta-tags';
  import { page } from '$app/stores';
  import extend from 'just-extend'; // Please provide functions that allow deep merging of objects, such as lodash.merge, deepmerge, just-extend.

  export let data;

  $: metaTags = extend(true, {}, data.baseMetaTags, $page.data.pageMetaTags);
</script>

<MetaTags {...metaTags} />

<slot />
```

v4

`+layout.svelte`
```svelte
<script>
  import { page } from '$app/stores';
  import { MetaTags, deepMerge } from 'svelte-meta-tags';

  let { data, children } = $props();

  let metaTags = $derived(deepMerge(data.baseMetaTags, $page.data.pageMetaTags));
</script>

<MetaTags {...metaTags} />

{@render children()}
```

**Comment by fromaline** [comment]
Thanks for your work! Great package!

**Comment by cowboycodr** [comment]
What's the status on Svelte 5 support?

**Comment by oekazuma** [comment]
@cowboycodr 
Even at this point, svelte-meta-tags works with Svelte 5 projects.
We plan to release a version with full support for Svelte 5 as soon as possible after Svelte 5 is officially released.
