### ISSUE TITLE
How to update the title after streamed data resolves from `+page.server.ts`?

### ISSUE THREAD

**Issue by dihmeetree** [oekazuma/svelte-meta-tags#1040]
I'm using streaming functionality in SvelteKit on one of my routes (a profile page for example). I'm streaming user's profile data from a database in my `+page.server.ts` file, and then i'd like to update the page title to `{displayName} | MySite` (with the displayName coming from the db) for example once it's loaded. How would I do this with svelte-meta-tags?

I have the base tags (defined in my layout.ts file), and want to overwrite the title, description after the profile data is resolved.

Any assistance/guidance would be appreciated :)

**Comment by oekazuma** [comment]
Please provide minimum reproducible code.
We appreciate it if you can use SvelteLab or StackBlitz so we can share it.
