### ISSUE TITLE
are extra label/data tags supported for Twitter?

### ISSUE THREAD

**Issue by andrewljohnson** [oekazuma/svelte-meta-tags#1041]
**Is your feature request related to a problem? Please describe.**
I would like to show take advantage of certain Slack display features. It wasn't clear to me if this is unimplemented, or there is a way to do it.

**Describe the solution you'd like**
Support these tags:

<meta name="twitter:label1" content="Written by" />
<meta name="twitter:data1" content="Foo" />
<meta name="twitter:label2" content="Reading time" />
<meta name="twitter:data2" content="Bar" />

**Comment by oekazuma** [comment]
What tags should I set? 
 Please indicate documentation, etc.

 Meta tags that are not provided as a feature can be set using "Additional Meta Tags".

 https://github.com/oekazuma/svelte-meta-tags?tab=readme-ov-file#additional-meta-tags

**Comment by andrewljohnson** [comment]
Sorry! My message got cut off.

I may have done it wrong, but I think I tried additional meta tags. The tags I am looking for are: 

```
<!-- extra metadata for Slack unfurls -->
<meta name="twitter:label1" content="Written by" />
<meta name="twitter:data1" content="Salma Alam-Naylor" />
<meta name="twitter:label2" content="Reading time" />
<meta name="twitter:data2" content="3 minutes" />
```

I was referencing this post: https://whitep4nth3r.com/blog/level-up-your-link-previews-in-slack/

**Comment by oekazuma** [comment]
If there are many requests for additions, we would like to adopt them as official features, but since their use is limited, please use “Additional Meta Tags” to handle them.

We have created an example.
https://svelte.dev/repl/6f245d634cc14e37ad7c1e2a2d699207?version=4.2.15

**Comment by andrewljohnson** [comment]
thanks, your support was above and beyond what was called for!
