### ISSUE TITLE
Using $page in +layout.svelte ??

### ISSUE THREAD

**Issue by KyleFontenot** [oekazuma/svelte-meta-tags#1058]
**Describe the bug**

When following the documentation, it uses `$page` in a `+layout.svelte` file, thuogh it throws an error from Sveltekit:
```
error: Cannot subscribe to 'page' store on the server outside of a Svelte component, as it is bound to the current request via component context. This prevents state from leaking between users. For more information,
```

**Reproduction**
Provide a reproduction URL or steps to reproduce. If a report is vague and no reproduction is provided within a reasonable time-frame, the issue will be closed.

Steps: use `$page` in a `+layout.svelte` file such as the official documentation says:
```
<script>
...
  $: metaTags = mergeObjects(true, {}, data.baseMetaTags, $page.data.pageMetaTags) as MetaTagsProps;
</script>
```

**Additional context**

I'm not sure what workaround I have at my disposal if Svelte kit is throwing this error because of leaking state between users. I'm assuming this setup would work prerendered

**Comment by oekazuma** [comment]
I have tried to create an example, but the problem is not reproduced.
https://stackblitz.com/edit/sveltejs-kit-template-default-uftfum?file=src%2Froutes%2F%2Blayout.svelte

I checked and it seems that deleting the `.svelte-kit` folder once might work.

**Comment by KyleFontenot** [comment]
> I checked and it seems that deleting the `.svelte-kit` folder once might work.

Deleting `.svelte-kit` worked!
Thank you!
