### ISSUE TITLE
Yarn peer requirements

### ISSUE THREAD

**Issue by fromaline** [oekazuma/svelte-meta-tags#1104]
**Describe the bug**
Hey! Thanks for the library 🙏

I'm experiencing a minor issue with peer requirements:
```
✘ svelte-meta-tags@npm:3.1.2 [eb885] doesn't provide typescript to schema-dts@npm:1.1.2
```
It's not a big deal at all, just a minor annoying thing :)

**Reproduction**
Run this command in the project with svelte-meta-tags dependency
```sh
yarn install
```

You'll get an error
```
Some peer dependencies are incorrectly met by dependencies; run yarn explain peer-requirements for details.
```

Then run
```sh
yarn explain peer-requirements
```

**Comment by oekazuma** [comment]
Thanks for the report!

I tried to reproduce it using StackBlitz, but it didn't work.

https://stackblitz.com/edit/sveltejs-kit-template-default-epkdut?file=package.json

Please let me know if there are any conditions that are missing.

**Comment by fromaline** [comment]
Thanks for answering!

It's my bad! I'm using yarn modern, specifically `v4.3.1`.
Maybe that's the reason. It seems like StackBlitz only supports yarn v1.

**Comment by oekazuma** [comment]
I was able to confirm it locally.
Hmm. I'm not sure what to do.
As a solution, I think it would be good to include typescript in the dependencies and peerDependencies, but this would increase the number of dependencies and force the use of typescript.
If it is working without any problems, I couldn't see any errors in pnpm or npm, so I'd like to leave it as it is.

**Comment by fromaline** [comment]
I'm not sure whether including typescript as a dependency would force the use of typescript 🤷‍♂️
But that definitely will increase the number of dependencies!

> If it is working without any problems, I couldn't see any errors in pnpm or npm, so I'd like to leave it as it is.

Yep, no errors on my side too. Just a minor warning. For example, `@sentry/sveltekit` triggers the same warning 😄

**Comment by oekazuma** [comment]
I will close it for now.
If something major happens, I will think about how to deal with it.
