### ISSUE TITLE
Add support for sapper/svelte-kit

### ISSUE THREAD

**Issue by oneserv-heuser** [oekazuma/svelte-meta-tags#113]
**Is your feature request related to a problem? Please describe.**
The problem is that this awesome package is not usable in sapper/svelte-kit as most properties are static. [Version 2.1](https://github.com/oekazuma/svelte-meta-tags/releases/tag/v2.1.0) added support for a dynamic title but the rest of the properties are static.

For example I'm using stores to set the meta tags like this:
```SVELTE
 <meta name="robots" content={$robots}/>
```
With this module I can set them like this:
```SVELTE
<MetaTags robots={$robots} />
```

If I navigate now through my website and update the robot store, the value in the meta tag doesn't get updated when using this package. Using my own solution works.

**Describe the solution you'd like**
All properties should be dynamic so that on site navigation they can change.

**Comment by oekazuma** [comment]
Hi. Thanks for the suggestion!

I would love to do making all properties dynamic, but I myself have recently had a baby and am concentrating on raising my child, so I don't have time to work on it. Can you please wait until I get settled or send me a pull request so I can do the review and merge in my free time?

**Comment by oneserv-heuser** [comment]
@oekazuma I'll have a look at it. 
Congratulations on the birth!

**Comment by oneserv-heuser** [comment]
Well, just looked into the code. It's already reactive and working. Was my fault as I just passed the robots as "robots" property instead of using "noindex" and "nofollow". So the support is already there 😆
