### ISSUE TITLE
Adding Meta Theme Colour tag.

### ISSUE THREAD

**Issue by SanjaiyanUnofficial** [oekazuma/svelte-meta-tags#126]
Hi, adding `<meta name="theme-color" content={colour} />`. 🎨 

Extremely sorry if I made any mistake.

**Comment by oekazuma** [comment]
Please use [Additional Meta Tags](https://github.com/oekazuma/svelte-meta-tags#additional-meta-tags).

You can use it by writing the following example.

```svelte
<script>
 import { MetaTags } from 'svelte-meta-tags';
</script>

<MetaTags
 additionalMetaTags={[
  {
   name: 'theme-color',
   content: '#4285f4'
  }
 ]}
/>
```
