### ISSUE TITLE
question: is there any reason to limit this package installation for pnpm only?

### ISSUE THREAD

**Issue by sozonome** [oekazuma/svelte-meta-tags#154]
Hi, I really like this package as it's really like a next-seo equivalent for svelte projects, love what you're doing here.

One issue: I can't install this package unless I use pnpm. Pnpm is really a great choice and its blazing fast. But I believe there're some people out there (including me) who are still relying on yarn / npm as it's more supported for integrations with other platforms / toolings (deployment, automatic dependency updater, etc which not many have supported pnpm yet).

I see there's a commit where it's limit to use pnpm only: https://github.com/oekazuma/svelte-meta-tags/commit/afb29dd722f1e23aec8280944d1f72c7489f3a4f

Really appreciate if there're some explanations / reasons for it 🙏

**Comment by oekazuma** [comment]
@sozonome 

Oh, sorry about that.

I wanted to be able to use only pnpm when developing svelte-meta-tags, but I made a mistake in the configuration.

We have released a fixed version. [v2.2.2](https://github.com/oekazuma/svelte-meta-tags/releases/tag/v2.2.2)

Thank you for your report!

**Comment by sozonome** [comment]
> @sozonome
> 
> Oh, sorry about that.
> 
> I wanted to be able to use only pnpm when developing svelte-meta-tags, but I made a mistake in the configuration.
> 
> We have released a fixed version. [v2.2.2](https://github.com/oekazuma/svelte-meta-tags/releases/tag/v2.2.2)
> 
> Thank you for your report!

Thanks for the response and the updated release 🙏
