### ISSUE TITLE
in promise) SyntaxError: The requested module '/node_modules/.pnpm/svelte-meta-tags@2.3.3_svelte@3.46.4+typescript@4.6.2/node_modules/svelte-meta-tags/index.js' does not provide an export named 'MetaTags'

### ISSUE THREAD

**Issue by bitdom8** [oekazuma/svelte-meta-tags#246]
Thanks for this great repo.

in promise) SyntaxError: The requested module '/node_modules/.pnpm/svelte-meta-tags@2.3.3_svelte@3.46.4+typescript@4.6.2/node_modules/svelte-meta-tags/index.js' does not provide an export named 'MetaTags'

get this error with latest sveltekit

**Comment by oekazuma** [comment]
Thanks for reporting 👍 @bitdom8 

🎉 This issue has been resolved in version 2.3.4 🎉

The release is available on:

[npm package (@latest dist-tag)](https://www.npmjs.com/package/svelte-meta-tags/v/2.3.4)
[GitHub release](https://github.com/oekazuma/svelte-meta-tags/releases/tag/v2.3.4)

**Comment by bitdom8** [comment]
Ach thanks, you are very fast
