### ISSUE TITLE
Twitter:image

### ISSUE THREAD

**Issue by shinokada** [oekazuma/svelte-meta-tags#461]
According to the [Twitter doc](https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/summary), the image ratio changed to 1:1.
The current README has 2:1.

> A URL to a unique image representing the content of the page. You should not use a generic image such as your website logo, author photo, or other image that spans multiple pages. Images for this Card support an aspect ratio of 1:1 with minimum dimensions of 144x144 or maximum of 4096x4096 pixels. Images must be less than 5MB in size. The image will be cropped to a square on all platforms. JPG, PNG, WEBP and GIF formats are supported. Only the first frame of an animated GIF will be used. SVG is not supported.

**Comment by oekazuma** [comment]
Thank you.

I have updated the documentation.
