### ISSUE TITLE
Unknown file extension .svelte after upgrading to Svelte 3.52

### ISSUE THREAD

**Issue by ktecho** [oekazuma/svelte-meta-tags#485]
**Describe the bug**

After upgrading to Svelte 3.52.0, svelte-meta-tags cannot be used anymore. I've seen 2 different problems:

```
Unknown file extension ".svelte" for /route-to-project/web/node_modules/svelte-meta-tags/MetaTags.svelte
```
or
```
Cannot find module 'svelte-meta-tags' imported from '/route-to-project/web/src/lib/components/ComponentName.svelte'
```

After looking for it in the Internet, I've seen several reports on how to fix it (like [this one](https://github.com/JustinVoitel/svelte-hero-icons/issues/18)).

I've seen [this commit of you](https://github.com/oekazuma/svelte-meta-tags/commit/cd0574cf04050d3f8a031556ff20628aa390c671) that already was adding the needed properties, but if I look at `package.json` in v2.6.3 of this plugin, I must change this:

```
  },
  "svelte": "./index.js",
}
```

into this:

```
  },
  "svelte": "./index.js",
  "main": "./index.js"
}
```

Then it starts working fine again.

So I don't know who builds package.json, but it seems it's forgetting to add the "main" line?

**Comment by oekazuma** [comment]
I have tried with stackblitz but cannot get a reproduction.

https://stackblitz.com/edit/vitejs-vite-2pckze?file=src/App.svelte

If the problem continues to occur, please provide a repository where it can be reproduced.

**Comment by ktecho** [comment]
I guess I had something setup badly. Now it's working, so I'm closing the bug. Thanks a lot for trying to reproduce it!
