### ISSUE TITLE
Schema Can be an Array

### ISSUE THREAD

**Issue by jdgamble555** [oekazuma/svelte-meta-tags#549]
A JSON-LD schema can be an array of items.  This should be accepted:

https://stackoverflow.com/a/32954313/271450
https://stackoverflow.com/questions/48294593/how-do-you-combine-several-json-ld-markups/48295719#48295719

If it is an array, the @context could be added to each item.

___

Here is one option:

```js
	// create schema with context
	function createSchema(schema: any) {
		// add context
		const addContext = (c: any) => ({ '@context': 'http://schema.org', ...c });

		// handle object
		if (!Array.isArray(schema)) {
			return addContext(schema);
		}

		// handle array
		schema = schema.map((v) => addContext(v));
		return schema.length === 1 ? schema[0] : schema;
	}

	$: json = `${'<scri' + 'pt type="application/ld+json">'}${JSON.stringify(createSchema(schema))}${
		'</scri' + 'pt>'
	}`;
```

J

**Comment by oekazuma** [comment]
I think this is a good suggestion.
I will work on it when I have time.

For now, this can be handled by writing multiple `<JsonLd />`.
