### ISSUE TITLE
either im stupid or the og:image isnt working, how do i get that to show no matter what i do i cant find a way to have the image i made be displayed as the image you see when you share the link to my website

### ISSUE THREAD

**Issue by MrsHorrid** [oekazuma/svelte-meta-tags#625]
**Describe the bug**

**Reproduction**
Provide a reproduction URL or steps to reproduce. If a report is vague and no reproduction is provided within a reasonable time-frame, the issue will be closed.

**Additional context**

**Comment by oekazuma** [comment]
I cannot help you because you have not explained what code you are running and what the situation is.
If you are serious about seeking help, please provide more detailed information.

**Comment by MrsHorrid** [comment]
> I cannot help you because you have not explained what code you are running and what the situation is.
> If you are serious about seeking help, please provide more detailed information.

Sorry already solved it... The servers simply chached for a while thanks for the reply tho
