### ISSUE TITLE
Add charset attribute

### ISSUE THREAD

**Issue by Dameck** [oekazuma/svelte-meta-tags#668]
To define the character encoding (HTML5):

`<meta charset="utf-8">`

Maybe like this:

`<MetaTags charset="utf-8" />`

Thanks 🤝

**Comment by oekazuma** [comment]
It would be easy to add this feature, but since most people use SvelteKit and define `<meta charset="utf-8">` in `app.html`, it seems unnecessary.

The following code will accomplish the same thing.

```svelte
<MetaTags
  additionalMetaTags={[
    {
      httpEquiv: 'content-type',
      content: 'text/html; charset=UTF-8',
    },
  ]}
/>
