### ISSUE TITLE
Og:image:width

### ISSUE THREAD

**Issue by bitdom8** [oekazuma/svelte-meta-tags#69]
Hi, can you add og:image:width and og:image:height?

**Comment by oekazuma** [comment]
I think you can already do that.
Here's an example, check it out.
https://github.com/oekazuma/svelte-meta-tags#basic

**Comment by bitdom8** [comment]
Thanks @oekazuma . Using facebook debug tool it states: 
The provided 'og:image' properties are not yet available because new images are processed asynchronously. To ensure shares of new URLs include an image, specify the dimensions using 'og:image:width' and 'og:image:height' tags.

**Comment by bitdom8** [comment]
Understood now, facebook caches that is why need to remove cookies and also share it on my personal profile, make it work. Thanks @oekazuma
