### ISSUE TITLE
Keywords metatags

### ISSUE THREAD

**Issue by ambigos1** [oekazuma/svelte-meta-tags#701]
**Keywords metatags**

Meta keywords are meta tags that you can use to give search engines more information about a page's content

Currently there is no option to add Keywords to the MetaTag since it does not exist in type 'MetaTagsProps'

is there an option to support this kind of feature?

it is really easy to add it to this library and it really can boost your seo score.

**Comment by oekazuma** [comment]
This can be accomplished by simply setting the value of the `additionalMetaTags` property!
However, this may not be good for SEO as Google has announced that they will not use `keywords meta tags`.
https://developers.google.com/search/blog/2009/09/google-does-not-use-keywords-meta-tag

```svelte
<MetaTags
  additionalMetaTags={[
    {
      name: 'keywords',
      content: 'keyword',
    }
  ]}
/>
```

**Comment by ambigos1** [comment]
Well, This is something I did not know.
Thanks for sharing the information.

I will still use this keyword's meta tag because accordingly to what he said in the YouTube video there is still a chance that other search engines use it.

Thanks for the fast response and for helping me with the solution.
