### ISSUE TITLE
Duplicate Json+ld in the bottom of the page

### ISSUE THREAD

**Issue by VisionaryAppDev** [oekazuma/svelte-meta-tags#702]
**Describe the bug**
Previously, I got Json+ld duplication in the header section of the HTML as everyone has reported. But after the update, it was gone until I saw Google Webmaster point out another duplication issue. 

**Reproduction**
I have tried view-source tab, but I couldn't find it. But, when press F12 -> Element tab and search for specific schema.org tag like FAQPage, then I found one of the duplication at the bottom of my page and it's highlighted that it's added by a js file.  Here is the page that I got every json+ld duplication issue [OnlineAppZone.com](https://www.onlineappzone.com). 

![Screenshot_20230601_100624](https://github.com/oekazuma/svelte-meta-tags/assets/27724011/6f3fabb4-1bf8-4956-9148-53add84a504e)

 

**Additional context**
svelte.config.js
```
...
import preprocess from "svelte-preprocess";

const config = {
 preprocess: [
    preprocess({
      postcss: true,
      preserve: ["ld+json"]
    })
  ]
};
```

package.json
```
...
"@sveltejs/kit": "^1.20.0",
"svelte": "^3.59.1",
"svelte-meta-tags": "^2.7.2",
"svelte-preprocess": "^5.0.4",
"vite": "^4.3.9"

```

**Comment by oekazuma** [comment]
I have checked the site you provided and there is indeed a duplication of elements.

This [issue](https://github.com/sveltejs/kit/issues/7493) may be helpful.

Since `<svelte:head>` seems to contain some bugs, please also consider the following option. It renders against `<body>`, which may solve the problem.

```svelte
<JsonLd output="body" schema={...} />
```

**Comment by oekazuma** [comment]
I believe the problem is with Svelte itself, so I will close in favor of the above temporary solution.

**Comment by dgrebb** [comment]
This thread just saved me time *and* money. Thank you all!
