### ISSUE TITLE
Conflicting results in svelte resolve configuration

### ISSUE THREAD

**Issue by TheOnlyTails** [oekazuma/svelte-meta-tags#736]
**Describe the bug**
Hi, i was working on my project that uses this library, and I got this warning, which told me to report the issue to the library maintainers:
```
[vite-plugin-svelte] WARNING: The following packages use a svelte resolve configuration in package.json that has conflicting results and is going to cause problems future.

svelte-meta-tags@2.8.0

Please see https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#conflicts-in-svelte-resolve for details.
```

**Reproduction**
my project is open source at https://github.com/theonlytails/aura-lang/tree/main/packages/aura-site

**Comment by oekazuma** [comment]
Thank you for your report!

I cloned the repository you reported and checked it, but did not see the same message.
Could you please elaborate on how to reproduce this?

I have looked at the `vite-plugin-svelte` documentation you provided and it should reflect what you have already written 🤔.

**Comment by TheOnlyTails** [comment]
I got the message the moment i stopped my dev server, so it might be a false positive, but i thought it better to report it to be sure

**Comment by oekazuma** [comment]
Thank you!

So far it didn't look like there was a problem, so I'm going to close it.
Please open again if you have any further questions.
