### ISSUE TITLE
[FEAT] - support/extend `robots` via `robotsProps.robots`

### ISSUE THREAD

**Issue by dgrebb** [oekazuma/svelte-meta-tags#753]
> I am looking to support a variety of use cases. However, we are concerned that adding a `robots` property would complicate the properties that affect the robots element.

> I'm still struggling with what to do, but I'm wondering if integrating the `robots` feature with the `robotsProps` feature might be a solution?

_Originally posted by @oekazuma in https://github.com/oekazuma/svelte-meta-tags/issues/750#issuecomment-1641479408_

**Comment by dgrebb** [comment]
Will take a look.

**Comment by oekazuma** [comment]
Close when done.
https://github.com/oekazuma/svelte-meta-tags/pull/789

We look forward to your feedback.
