### ISSUE TITLE
v3

### ISSUE THREAD

**Issue by oekazuma** [oekazuma/svelte-meta-tags#786]
Here is a summary of what needs to be done for v3.
Please give me any requests you would like to see added to v3.

- [x] 🔥 Remove the `googlebot` tag. If necessary, you can add it by using `Additional Meta Tags`
  - Related Issues #783
- [x] 🔧  More flexible customization of `robots`
  - Related Issues #753
- [x] ✨ Improved type definitions
  - Related Issues #796 
- [x] 👨‍💻 Migration to monorepo
  - Related Issues #794

### Migration Guide
- `noindex` and `nofollow` properties have been removed. They can be controlled by using the `robots` property instead. 

v2.x
```svelte
<MetaTags noindex={true} nofollow={true} />
```

v3
```svelte
<MetaTags robots="noindex,nofollow" />
```
- `googlebot` is no longer included by default, so if you want to continue to enable the `googlebot`, write the following.

```svelte
<MetaTags
  additionalMetaTags={[
    {
      name: 'googlebot',
      content: 'index,follow'
    }
  ]}
/>
```

- `<meta name="robots">` element can now be disabled completely.

```svelte
<MetaTags
  robots={false}
/>
```
If you want to disable `<meta name="robots">` and enable only `<meta name="googlebot">`, write the following.

```svelte
<MetaTags
  robots={false}
  additionalMetaTags={[
    {
      name: 'googlebot',
      content: 'index,follow'
    }
  ]}
/>
```
 

- `robotsProps` property has been renamed `additionalRobotsProps`.

v2.x
```svelte
<MetaTags
  robotsProps={{
    nosnippet: true,
    notranslate: true,
    noimageindex: true,
    noarchive: true,
    maxSnippet: -1,
    maxImagePreview: 'none',
    maxVideoPreview: -1
  }}
/>
```

v3
```svelte
<MetaTags
  additionalRobotsProps={{
    nosnippet: true,
    notranslate: true,
    noimageindex: true,
    noarchive: true,
    maxSnippet: -1,
    maxImagePreview: 'none',
    maxVideoPreview: -1
  }}
/>
```

**Comment by watanabemasahiro128** [comment]
@oekazuma 
How about also adding a way to allow only `googlebot` tag to be set?
I think there is a demand for such.

**Comment by oekazuma** [comment]
@watanabemasahiro128 
I am working on it, but will be able to enable only `googlebot` by writing the following.

```svelte
<MetaTags
  robots={false}
  additionalMetaTags={[
    {
      name: 'googlebot',
      content: 'index,follow'
    }
  ]}
/>
```

**Comment by watanabemasahiro128** [comment]
@oekazuma 
I see, you have created a new pull request.
Thank you.

**Comment by OllieJT** [comment]
What was the motivation behind moving from snake_case to camalCase?

**Comment by oekazuma** [comment]
1. because site_name will be removed and siteName will be adopted in the next major version of [next-seo](https://github.com/garmeeh/next-seo/blob/f8b907f1b047b1844fd04a7e549d6589868e11ac/src/types.ts#L242).
2. since only site_name had adopted the snake case, its interface was aligned with other properties.

**Comment by baseplate-admin** [comment]
>1. because site_name will be removed and siteName will be adopted in the next major version of [next-seo](https://github.com/garmeeh/next-seo/blob/f8b907f1b047b1844fd04a7e549d6589868e11ac/src/types.ts#L242).

Are we following the development of `next-seo`?

**Comment by oekazuma** [comment]
It does not completely follow next-seo, but it is at least a major SEO library.

I believe the move from React to Svelte should be welcomed.

I think this change is reasonable and I only mention it as one reason
