### ISSUE TITLE
What's on the roadmap?

### ISSUE THREAD

**Issue by baseplate-admin** [oekazuma/svelte-meta-tags#821]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when i don't see a roadmap for a project.

**Describe the solution you'd like**
Project should have a roadmap.

**Describe alternatives you've considered**
Project not having a roadmap.

**Additional context**
Most of the open source project i have come across have a roadmap.

Jokes aside, the project is actually awesome. It would be better if there was some planning for this project :)

**Comment by oekazuma** [comment]
I have no ideas to draw a roadmap at this time.
I use this library in my work and so far I haven't had any trouble with it.
I may draw up another roadmap if someone submits an idea or if Svelte5 is released.
