### ISSUE TITLE
og:type is not working

### ISSUE THREAD

**Issue by xxxhussein** [oekazuma/svelte-meta-tags#907]
**Describe the bug**

in `+layout.svelte`

```
<MetaTags
    titleTemplate="%s - App"
    openGraph={{
        type: "website",
        url: href,
    }}
    canonical={href}
    {...$page.data.metaTagsChild}
/>
```

all tags are working except `openGraph.type`

**Comment by oekazuma** [comment]
Can you give us some more details?
What is the value of `$page.data.metaTagsChild`?

**Comment by xxxhussein** [comment]
> Can you give us some more details? What is the value of `$page.data.metaTagsChild`?

its different for every page but its something like this

```ts
export const load = () => {
    const metaTags: MetaTagsProps = {
        title: "Home",
        openGraph: {
            title: "Home",
        },
        twitter: {
            title: "Home",
        },
    };

    return {
        metaTagsChild: metaTags,
    };
};
```

**Comment by oekazuma** [comment]
Sorry, there was an error in the documentation.
Java Script usually does not allow deep merging of objects, so you need to have a function that allows deep merging.

Please refer to the detailed example I have created.
https://github.com/oekazuma/svelte-meta-tags/tree/main/example
