### ISSUE TITLE
onHide log was removed but a new version wasn't published

### ISSUE THREAD

**Issue by TGilany** [oekazuma/svelte-meta-tags#917]
**Describe the bug**
Console log is spamming with `onHide` message.
A fix was merged to PROD but a version wasn't published.

**Additional context**
https://github.com/svelte-plugins/tooltips/commit/06a0c2dacb9e03ad812295c52a2f9024321ce659

**Comment by oekazuma** [comment]
It appears that you are creating the issue in the wrong place.
This is the svelte-meta-tags repository.
