### ISSUE TITLE
Not providing title property creates empty title tag

### ISSUE THREAD

**Issue by laszlo1337** [oekazuma/svelte-meta-tags#975]
**Describe the bug**
If meta tags config does not include `title` property, the library will create empty `<title></title>` tag, which is unwanted in my opinion, because somebody (like me) could need to supply title on each individual page. In my case my website is translated meaning the titles are also translated dynamically by svelte-i18n, so naturally I need to access the locale stores in page component. I want to use the baseMetaTags approach from the readme example.

**Reproduction**
```
function getBaseTags(url) {
	const pageUrl = decodeURIComponent(new URL(url.pathname, url.origin).href)
	const description = 'Desc'
	return Object.freeze({
		description,
		canonical: pageUrl,
		openGraph: {
			type: 'website',
			url: pageUrl,
			locale: 'pl',
			title: 'AppName',
			description,
			siteName: 'AppName',
			images: [
				{
					url: `${url.origin}/meta_image_half.png`,
					width: 600,
					height: 315,
					type: 'image/png',
				},
				{
					url: `${url.origin}/meta_image_half.png`,
					width: 1200,
					height: 630,
					type: 'image/png',
				},
			],
		},
	})
}
```
result:
![image](https://github.com/oekazuma/svelte-meta-tags/assets/24696743/e314b84b-ef89-41cf-9ec4-59574578dbd6)

**Additional context**
I'm not sure how crawlers will react to having two title tags in head - could they grab the empty one first?

**Comment by oekazuma** [comment]
Thanks for the report!
A corrected version has been released.

https://github.com/oekazuma/svelte-meta-tags/releases/tag/svelte-meta-tags%403.1.1
